# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/sweri/Desktop/HD/final/Final Project/cons.xdc

# IP: ip/mem_GAME_START/mem_GAME_START.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mem_GAME_START || ORIG_REF_NAME==mem_GAME_START} -quiet] -quiet

# IP: ip/mem_FPCAT/mem_FPCAT.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mem_FPCAT || ORIG_REF_NAME==mem_FPCAT} -quiet] -quiet

# XDC: c:/Users/sweri/Desktop/HD/final/Final Project/projectRG/projectRG.gen/sources_1/ip/mem_GAME_START/mem_GAME_START_ooc.xdc

# XDC: c:/Users/sweri/Desktop/HD/final/Final Project/projectRG/projectRG.gen/sources_1/ip/mem_FPCAT/mem_FPCAT_ooc.xdc
